version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: context-example-postgres
    environment:
      POSTGRES_DB: contextdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
